apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo3-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lukaj-master/demo3.git
    targetRevision: refs/heads/master
    path: k8s-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: demo3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true